# Generated by Django 4.1.7 on 2023-04-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('image', models.ImageField(upload_to='divan/', verbose_name='изображение')),
                ('cost', models.IntegerField(verbose_name='цена')),
                ('about', models.TextField(verbose_name='описание')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Диван',
                'verbose_name_plural': 'Диваны',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('count', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('size', models.SmallIntegerField(choices=[('small', 'маленький'), ('medium', 'средний'), ('big', 'большой')])),
                ('divan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='soft.divan')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='divan',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft.type', verbose_name='тип'),
        ),
    ]
