# Generated by Django 4.1.7 on 2023-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
        migrations.AlterField(
            model_name='divan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divan/', verbose_name='изображение'),
        ),
    ]
